import "./search";
import "./header";
import "./aside";
import "./burger";
import "./slider";
import "./mobile-menu";
import "./copy-and-share";
import "./single-progress";
import "./popup";
import "./blue-popup";
import "./iframe-time";
// import "./preloader";
import "./sport-quiz";
